import Layout from "@/components/layout";
import About from "@/components/organisms/about/about";
import Hero from "@/components/organisms/hero/hero";
import Services from "@/components/organisms/services/services";
import Skills from "@/components/organisms/skills/skills";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Hero />
          <About />
          <Services />
          <Skills />
        </Layout>
      </main>
    </>
  );
}
