import Loading from "@/components/atoms/shared/loading";
import Layout from "@/components/layout";
import About from "@/components/organisms/about/about";
import Contact from "@/components/organisms/contact/contact";
import Hero from "@/components/organisms/hero/hero";
import Projects from "@/components/organisms/projects/projects";
import Services from "@/components/organisms/services/services";
import Skills from "@/components/organisms/skills/skills";
import Testimonials from "@/components/organisms/testimonials/testimonials";
import Timeline from "@/components/organisms/timeline/timeline";
import { useGlobalContext } from "@/contexts/globalContext";
import Head from "next/head";

export default function Home() {
  const { profile } = useGlobalContext();

  return (
    <>
      <Head>
        <title>Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Hero />
          <About />
          <Services />
          <Skills />
          <Projects />
          <Timeline />
          <Testimonials />
          <Contact />
        </Layout>
      </main>
    </>
  );
}
